use_frameworks!
platform :ios, '8.0'
pod 'SDWebImage'
pod 'Alamofire'
pod 'SSKeychain'
pod 'FFAutoLayout'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'Bugtags'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'DGElasticPullToRefresh'
