use_frameworks!
platform :ios, '8.0'
pod 'SDWebImage'
pod 'Alamofire'
pod 'FFAutoLayout'
pod 'JGProgressHUD'
pod 'MJRefresh'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'YTKKeyValueStore'
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
